=== hbz/lobid/schemas/publication.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "resource:/publication.json",
  "title": "prodPublicationuct",
  "description": "Schema to describe a publication (blog post, slidedeck, journal article etc.).",
  "type": "object",
  "properties": {
    "@context": {
      "$ref": "resource:/context.json"
    },
    "id": {
      "$ref": "resource:/id.json"
    },
    "type": {
      "type": "string",
      "enum": [
        "BlogPosting",
        "PresentationDigitalDocument",
        "Article"
      ]
    },
    "name": {
      "$ref": "localizedString.json"
    },
    "description": {
      "$ref": "localizedString.json"
    },
    "keywords": {
      "title": "Keywords",
      "description": "Keywords/tags for a publication",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "about": {
      "$ref": "resource:/about.json"
    },
    "creator": {
      "$ref": "resource:/creator.json"
    },
    "datePublished": {
      "title": "Publication date",
      "description": "The publication date of a creative work",
      "$ref": "resource:/datePublished.json"
    },
    "inLanguage": {
      "$ref": "resource:/inLanguage.json"
    },
    "license": {
      "$ref": "resource:/license.json"
    }
  },
  "required": [
    "name",
    "id"
  ]
}

=== hbz/lobid/gatsby/lobid/static/publication/2020-08-oersi-skohub.json
{
  "@context": "https://schema.org",
  "type": "PresentationDigitalDocument",
  "name": {
    "de": "OERSI & SkoHub"
  },
  "creator": [
    {
      "id": "http://lobid.org/team/ap#!",
      "type": "Person",
      "name": "Adrian Pohl"
    }
  ],
  "description": {
    "de": "Pr√§sentation am 2020-08-26"
  },
  "keywords": [
    "oer",
    "open educational resources",
    "resource discovery",
    "oersi",
    "skohub"
  ],
  "about": [
    {
        "id": "https://lobid.org/project/oersi"
    },
    {
      "id": "https://lobid.org/product/skohub"
    }
],
  "id": "http://slides.lobid.org/2020-08-oersi-skohub/",
  "datePublished": "2020-08-24",
  "inLanguage": [
    "de"
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}

=== hbz/lobid/examples/publication/valid/libreas2016.json
{
  "@context": "https://schema.org",
  "type": "Article",
  "name": {
    "de": "Zurück ins Web. Die Entwicklung eines neuen Webauftritts für die Nordrhein-Westfälische Bibliographie (NWBib)"
  },
  "creator": [
    {
      "id": "http://lobid.org/team/ap#!",
      "type": "Person",
      "name": "Adrian Pohl"
    },
    {
      "id": "http://lobid.org/team/fs#!",
      "type": "Person",
      "name": "Fabian Steeg"
    }
  ],
  "description": {
    "de": "Am Hochschulbibliothekszentrum des Landes Nordrhein-Westfalen (hbz) wird seit Anfang 2014 nach Vorgaben und unter Begutachtung der Universitäts- und Landesbibliotheken in Düsseldorf, Münster und Bonn ein neuer Webauftritt für die Landesbibliographie Nordrhein-Westfalens, die Nordrhein-Westfälische Bibliographie (NWBib) entwickelt. Die Entwicklung basiert auf der Web-Schnittstelle des Linked-Open-Data-Dienst lobid und wird vollständig mit Open-Source-Software entwickelt. Aus der Perspektive des Entwicklungsteams am hbz beschreibt der Artikel Kontext und Durchführung des Projekts. Der Beitrag skizziert die historische Entwicklung der NWBib mit Fokus auf die Beziehung der Bibliographie zum World Wide Web (WWW), erläutert die Voraussetzungen für die Neuentwicklung sowie die Leitlinien des Entwicklungsprozesses, gibt einen Überblick über die Nutzung des neuen Webauftritts und die zur Umsetzung verwendete Technologie. Abgeschlossen wir der Artikel mit Lessons-Learned und einem Ausblick auf weitere Entwicklungen."
  },
  "about": [
    {
      "id": "https://nwbib.de"
    }
  ],
  "id": "https://libreas.eu/ausgabe29/04pohl/",
  "datePublished": "2016",
  "inLanguage": [
    "de"
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}

=== hbz/lobid/gatsby/lobid/static/publication/lobid-gnd-https-change.json
{
  "@context": "https://schema.org",
  "type": "BlogPosting",
  "name": {
    "de": "GND: Umstellung auf HTTPS-URIs"
  },
  "creator": [
    {
      "id": "http://lobid.org/team/ap#!",
      "type": "Person",
      "name": "Adrian Pohl"
    }
  ],
  "about": [
    {
      "id": "https://lobid.org"
    }
  ],
  "id": "https://blog.lobid.org/2019/11/29/lobid-gnd-https-change.html",
  "datePublished": "2019-11-29",
  "inLanguage": [
    "de"
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}

=== hbz/lobid/examples/publication/valid/skohub-apconf.json
{
  "@context": "https://schema.org",
  "type": "BlogPosting",
  "name": {
    "en": "ActivityPub Conference 2020"
  },
  "creator": [
    {
      "id": "http://lobid.org/team/ap#!",
      "type": "Person",
      "name": "Adrian Pohl"
    },
    {
      "id": "https://twitter.com/literarymachine/",
      "type": "Person",
      "name": "Felix Ostrowski"
    }
  ],
  "about": [
    {
      "id": "https://skohub.io"
    }
  ],
  "id": "https://blog.lobid.org/2020/10/09/skohub-apconf.html",
  "datePublished": "2020-10-09",
  "inLanguage": [
    "en"
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}

=== hbz/lobid/examples/publication/valid/openrefine.json
{
  "@context": "https://schema.org",
  "type": "BlogPosting",
  "name": {
    "en": "Improved GND reconciliation for OpenRefine"
  },
  "creator": [
    {
      "id": "http://lobid.org/team/fs#!",
      "type": "Person",
      "name": "Fabian Steeg"
    }
  ],
  "about": [
    {
      "id": "https://lobid.org"
    }
  ],
  "id": "https://blog.lobid.org/2019/08/19/openrefine.html",
  "datePublished": "2019-08-19",
  "inLanguage": [
    "en"
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}

=== hbz/lobid/examples/publication/valid/skohub-editor.json
{
  "@context": "https://schema.org",
  "type": "BlogPosting",
  "name": {
    "en": "Presenting the SkoHub Editor"
  },
  "creator": [
    {
      "id": "http://lobid.org/team/ap#!",
      "type": "Person",
      "name": "Adrian Pohl"
    },
    {
      "id": "https://twitter.com/literarymachine/",
      "type": "Person",
      "name": "Felix Ostrowski"
    }
  ],
  "about": [
    {
      "id": "https://lobid.org"
    }
  ],
  "id": "https://blog.lobid.org/2020/03/31/skohub-editor.html",
  "datePublished": "2020-03-31",
  "inLanguage": [
    "en"
  ],
  "license": "https://creativecommons.org/licenses/by/4.0/"
}
